### PR TITLE
Staking: multitest improvements

### LINKED ISSUE #53: Test Suite is failing and no coverage report
Description
The test suite exhibits a failure of executing tests, indicating issues. Additionally, the absence of a coverage report implies a lack of information regarding test coverage.

Remediation
To rectify this issue, the recommended steps involve resolving the failing test cases and integrating a library such as `cargo-llvm-cov` or `tarpaulin` to generate a comprehensive coverage report.

### PR DESCRIPTION
**Pull request by ueco-jb**

### CODE REVIEW

File: contracts/stake/src/multitest/delegate.rs [hunk 1]
```diff
@@ -1,25 +1,29 @@
...
-        suite.query_balance_vesting_contract(user).unwrap(),
+        suite.query_balance_vesting_contract(USER).unwrap(),
         100_000u128
     );
 
     // delegate half of the tokens, ensure they are staked
-    suite.delegate(user, 50_000u128, None).unwrap();
-    assert_eq!(suite.query_staked(user, None).unwrap(), 50_000u128);
+    suite.delegate(USER, 50_000u128, None).unwrap();
+    assert_eq!(suite.query_staked(USER, None).unwrap(), 50_000u128);
```
Comment (ueco-jb) [inline contracts/stake/src/multitest/delegate.rs]: Don't hardcode the amounts for the whole file when you are using later some different amounts. It makes it more difficult to make sure the test is correct.

File: contracts/stake/src/multitest/suite.rs [hunk 2]
```diff
@@ -1,27 +1,29 @@
-use std::collections::HashMap;
+use std::{collections::HashMap, ops::Add};
```
Comment (ueco-jb) [inline contracts/stake/src/multitest/suite.rs]: What is this for?

Comment (gangov) [reply contracts/stake/src/multitest/suite.rs]: I might have added it by accident, or it is there from before. Removing it

File: contracts/stake/src/multitest/delegate.rs (hunk 1 above)
Comment (gangov) [reply contracts/stake/src/multitest/delegate.rs]: I explicitly came back and made those as const values. Undo the one for amount, let me know if the rest needs to be undone as well.

**Comment by gangov** [comment]
a few words to this PR - I've removed a number of tests, judging that the implementation doesn't have to be tested since it's not in multitest/suite.rs

I have not tested the migration.rs because of that

I cannot add you as a reviewer for some reason @ueco-jb

File: contracts/stake/src/multitest/quick_unbond.rs [hunk 3]
```diff
@@ -202,82 +193,17 @@ fn control_case() {
...
-    assert_eq!(
-        ContractError::Unauthorized {},
-        suite
-            .quick_unbond(ADMIN, &[VOTER1])
-            .unwrap_err()
-            .downcast()
-            .unwrap(),
-        "no one should be able to quick unbond"
-    );
-}
```
Comment (gangov) [inline contracts/stake/src/multitest/quick_unbond.rs:249]: here we do quick_unbond, that's not longer used and we are supposed to verify the error `ContractError::Unauthorized`

unlike [quick_unbond](https://github.com/WHELP-project/whelp-contracts/blob/69301d542681ca84c9e25852efcbbf7183e4dd93/contracts/stake/src/contract.rs#L625) the fn [unbond](https://github.com/WHELP-project/whelp-contracts/blob/69301d542681ca84c9e25852efcbbf7183e4dd93/contracts/stake/src/contract.rs#L573) does not check if the caller is authorized

should we change that?

File: contracts/stake/src/multitest/distribution.rs [hunk 4]
```diff
@@ -145,200 +119,14 @@ fn multiple_distribution_flows() {
         .create_distribution_flow(
             "admin",
             &members[0],
-            AssetInfo::Token(dex_token.to_string()),
```
Comment (ueco-jb) [inline contracts/stake/src/multitest/distribution.rs:148]: Why did you remove this whole part of the test? It was testing distribution with 3 different tokens used in different timestamps.

Comment (gangov) [reply contracts/stake/src/multitest/distribution.rs:148]: but right now we also should have the same - a total of 3 distributions for juno, luna and dex tokens

Comment (gangov) [reply contracts/stake/src/multitest/distribution.rs:148]: brought back a bunch of tests.

**Comment by gangov** [comment]
tests not brought back, because their msgs are no longer used:
- delegate.rs: delegate_as_properly_assigned()
- distribution.rs: funds_withdrawal_delegation(), rebond_works(), rebond_multiple_works()
- quick_unbond.rs: quick_unbond_case() renamed to unbond() removed now; non_staker_works(), unbonder_permission_check()
- unbond_all.rs: mass_delegation_with_unbond_all_flag(), rebond_with_unbond_all_flag()

File: contracts/stake/src/multitest/distribution.rs [hunk 5]
```diff
@@ -798,7 +763,8 @@ fn calculate_apr() {
     let mut suite = SuiteBuilder::new()
         .with_unbonding_periods(unbonding_periods.clone())
         .with_admin("admin")
-        .with_initial_balances(vec![(member1, 500_000_000), (member2, 500_000_000)])
+        .with_lp_share_denom("tia".to_string())
+        .with_native_balances("tia", vec![(member1, 500_000_000), (member2, 500_000_000)])
```
Comment (ueco-jb) [inline contracts/stake/src/multitest/distribution.rs:767]: I think this fragment right here shows how good and intuitive this suite builder is.

File: contracts/stake/artifacts/stake.wasm
Comment (ueco-jb) [inline contracts/stake/artifacts/stake.wasm:1]: To remove.

File: contracts/stake/src/multitest/distribution.rs [hunk 6]
```diff
@@ -1136,225 +1273,54 @@ fn apr_cw20() {
...
-    //     0
-    // );
-    assert_eq!(suite.query_balance(&members[0], "juno").unwrap(), 50);
-    assert_eq!(suite.query_balance(&members[1], "juno").unwrap(), 100);
-    assert_eq!(suite.query_balance(&members[2], "juno").unwrap(), 250);
-    assert_eq!(suite.query_balance(&members[3], "juno").unwrap(), 0);
-}
-
-#[test]
-fn divisible_amount_distributed_twice() {
```
Comment (ueco-jb) [inline contracts/stake/src/multitest/distribution.rs:1314]: Why were those tests removed?

File: contracts/stake/src/multitest/staking_rewards.rs [hunk 7]
```diff
@@ -132,454 +134,339 @@ fn one_user_multiple_unbonding_periods() {
...
-                },
-                StakedResponse {
-                    stake: Uint128::new(10_000),
-                    total_locked: Uint128::zero(),
-                    unbonding_period: 8000,
-                    cw20_contract: suite.token_contract(),
-                },
-            ]
-        }
-    );
```
Comment (ueco-jb) [inline contracts/stake/src/multitest/staking_rewards.rs:219]: This query should stay as well.

File: contracts/stake/src/multitest/staking_rewards.rs [hunk 8]
```diff
@@ -132,454 +134,339 @@ fn one_user_multiple_unbonding_periods() {
...
-                },
-                StakedResponse {
-                    stake: Uint128::new(20_000),
-                    total_locked: Uint128::zero(),
-                    unbonding_period: 8000,
-                    cw20_contract: suite.token_contract(),
-                },
-            ]
-        }
-    );
```
Comment (ueco-jb) [inline contracts/stake/src/multitest/staking_rewards.rs]: This works? Why was the assertion removed?

**Review by ueco-jb — COMMENTED** [review]
A couple comments @gangov , I think you removed a little bit too much.

File: contracts/stake/src/multitest/distribution.rs (hunk 6 above)
Comment (gangov) [reply contracts/stake/src/multitest/distribution.rs:1314]: when it comes to distribution.rs these are the tests that I did not bring back, because the Msg that we test is no longer included in the contract:
`funds_withdrawal_delegation()`, `rebond_works()` and `rebond_multiple_works()`

we no longer have delegate and rebond msg and we also talked about that in DMs

File: contracts/stake/src/multitest/staking_rewards.rs (hunk 8 above)
Comment (gangov) [reply contracts/stake/src/multitest/staking_rewards.rs]: I think after I removed too much the first time and then moved some of that code back in I took what was in the commit from 9th of November. Fixed now

File: contracts/stake/src/multitest/staking_rewards.rs (hunk 7 above)
Comment (gangov) [reply contracts/stake/src/multitest/staking_rewards.rs:219]: this test checks the rebonding - I didn't include that because of the `rebond` msg no longer being available

File: contracts/stake/src/multitest/delegate.rs (hunk 1 above)
Comment (ueco-jb) [reply contracts/stake/src/multitest/delegate.rs]: I'd say we shouldn't hardcode anything above the tests, because then you'll have some string in the error log and you can't see in the test case itself what exactly it is. And you have to scroll up.
But it's fine, leave it as it is.

**Review by ueco-jb — COMMENTED** [review]
LGTM
